# Generated by Django 5.2 on 2025-10-15 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_hotelbooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amenities',
        ),
        migrations.DeleteModel(
            name='HotelManager',
        ),
    ]
